apiVersion: v1
kind: Namespace
metadata:
  name: iot
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: reader-deployment
  namespace: iot
  labels:
    app: reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - name: reader
        image: jpsluna/python-iot:1.3
        command: ["python", "/mqtt/reader.py"]
---
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: writer-deployment
  namespace: iot
  labels:
    app: writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      containers:
      - name: writer
        image: jpsluna/python-iot:1.3
        command: ["python", "/mqtt/writer.py"]
---
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: broker-deployment
  namespace: iot
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: toke/mosquitto
        ports:
          - containerPort: 1883
---
kind: Service
apiVersion: v1
metadata:
  name: broker
  namespace: iot
spec:
  selector:
    app: broker
  ports:
  - protocol: TCP
    port: 1883
    targetPort: 1883
---
kind: Service
apiVersion: v1
metadata:
  name: broker-external
  namespace: iot
spec:
  selector:
    app: broker
  ports:
  - protocol: TCP
    port: 1883
    nodePort: 31883
  type: NodePort
